name: WhatsApp SDK CI

on:
  push:
    paths:
      - 'packages/whatsapp-sdk/**'
  pull_request:
    paths:
      - 'packages/whatsapp-sdk/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/whatsapp-sdk

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build SDK
        run: npm run build
